<%@ Page Language="C#" AutoEventWireup="true" CodeFile="usersupdate.aspx.cs" Inherits="MEMBER_usersupdate" MasterPageFile="~/vcms.master" %>

<asp:Content ID="ctUserUpdate" ContentPlaceHolderID="CPH_MAIN" runat="server">


    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="UserId" DataSourceID="SqlDataSource1" EnablePersistedSelection="True" EnableSortingAndPagingCallbacks="True">
    <Columns>
        <asp:BoundField DataField="UserId" HeaderText="UserId" InsertVisible="False" ReadOnly="True" SortExpression="UserId" />
        <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
        <asp:BoundField DataField="FullName" HeaderText="FullName" SortExpression="FullName" />
        <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
        <asp:BoundField DataField="Uimage" HeaderText="Uimage" SortExpression="Uimage" />
        <asp:BoundField DataField="Groupid" HeaderText="Groupid" SortExpression="Groupid" />
        <asp:BoundField DataField="Birthday" HeaderText="Birthday" SortExpression="Birthday" />
        <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
        <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
        <asp:BoundField DataField="CreatedDate" HeaderText="CreatedDate" SortExpression="CreatedDate" />
        <asp:TemplateField ShowHeader="False">
            <ItemTemplate>
                <asp:LinkButton ID="LinkButton1" runat="server" CausesValidation="False" CommandName="Delete" Text="Delete" OnClientClick="return confirm('Bạn muốn xóa bản ghi này ?')" BorderStyle="Outset"></asp:LinkButton>
            </ItemTemplate>
        </asp:TemplateField>
    </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:vcms_cnn %>" DeleteCommand="SP_DELETE_USERS" DeleteCommandType="StoredProcedure" SelectCommand="SELECT [UserId], [Password], [FullName], [UserName], [Uimage], [Groupid], [Birthday], [Address], [Email], [CreatedDate] FROM [tbl_users]" UpdateCommand="SP_UPDATE_USERS" UpdateCommandType="StoredProcedure">
        <DeleteParameters>
            <asp:Parameter Name="UserID" Type="Int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="UserName" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="FullName" Type="String" />
            <asp:Parameter Name="Uimage" Type="String" />
            <asp:Parameter Name="GroupID" Type="Int32" />
            <asp:Parameter Name="BirthDay" Type="DateTime" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter Name="CreatedDate" Type="DateTime" />
        </UpdateParameters>
    </asp:SqlDataSource>

</asp:Content>
